# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: videoinstruct
  - model/reuse@reuse_module: default
  - model: reusevit
  - callbacks: default
  - logger: wandb
  - trainer: ddp
  - paths: default
  - extras: default
  - hydra: default

  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: null

  # config for hyperparameter optimization
  - hparams_search: null

  # optional local config for machine/user specific settings
  # it's optional since it doesn't need to exist and is excluded from version control
  - optional local: default

  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null

# task name, determines output directory path
task_name: "train"

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python train.py tags="[first_tag, second_tag]"`
tags: ["dev"]

# set False to skip model training
train: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: false

# simply provide checkpoint path to resume training
ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: null

# Evaluate inference model on val at epoch end
eval_infer:
  enabled: false
  max_batches: 1
  backend: local

# Slim checkpoints: keep only decision/restoration weights
checkpoint:
  # Default to slim checkpoints: base model reconstructed from Hugging Face
  save_trainable_only: true
  keep_patterns:
    - 'reuse_module.'
    - 'blobnet'
